#!/usr/bin/env bash
# Write PROVISIONAL gear tier files from item_template.
#
#   ./scripts/tournament/gear-generate.sh              # every combination below
#   ./scripts/tournament/gear-generate.sh warrior tank # just one
#
# base    = white (quality 1)
# upgrade = green (quality 2)
#
# Uniform basic white in every slot is the goal for the first tournament:
# completeness and fairness BY CONSTRUCTION. Every bot in every team wears the
# same grade of gear, no slot is empty, and a donation that buys "upgrade this
# bot" has a real, strictly better tier to move it into. Refinement -- stat
# weighting, set bonuses, a tank's shield -- is deferred until matches are
# actually running and you can see what looks wrong on screen; see the "Deferred
# work" section of docs/superpowers/plans/2026-08-16-03-gear-loadouts.md.
#
# Every generated file carries "provisional": true, so a curated file is
# distinguishable at a glance and by grep. The format does not change between the
# two -- only which integers sit in .tiers[].items -- which is exactly why
# curation can be deferred without blocking anything downstream.
#
# It picks mechanically: the highest item_level the class can actually equip in
# each slot at the tier's quality. It ABORTS rather than write a file with a hole
# in it. A tier missing a slot is the bug this whole path exists to fix
# (InitEquipment strips a bot and leaves unfillable slots empty,
# PlayerbotFactory.cpp:2999-3003), so producing one by hand would be worse than
# producing nothing.
#
# COLUMN NAMES ON THIS SERVER ARE snake_case -- entry, class, subclass, name,
# quality, inventory_type, allowable_class, item_level, required_level -- not the
# CamelCase (Quality, InventoryType, ItemLevel, RequiredLevel, AllowableClass)
# the plan text assumes; every one of those fails with `Unknown column`. The
# measurement and the full column list are in lib/itemdb.sh, which owns every
# query here.
#
# Needs the database container up (docker compose up -d db). Needs no server
# image and no build. Run from WSL, not Git Bash: jq is not on Git Bash's PATH.
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=lib/gear.sh
. "$HERE/lib/gear.sh"
# shellcheck source=lib/itemdb.sh
. "$HERE/lib/itemdb.sh"

# GEAR_DIR, not a private OUT_DIR: the library reads from it and gear_validate
# below re-reads what was just written, so a test or a dry run can point both at
# a scratch directory with one variable.
OUT_DIR="$GEAR_DIR"

BASE_QUALITY=1     # white
UPGRADE_QUALITY=2  # green

# No item_level cap. required_level <= 60 is the equippability gate (this world
# carries items with required_level up to 100), and the two flag guards in
# lib/itemdb.sh are what keep the dev item_level-90 sets out. An item_level
# ceiling on top of those would be a magic number doing nothing either of them
# does not already do.
NO_ILVL_CAP=999

# Every class/role combination the shipped tournament teams use. 12 files.
COMBOS='warrior|tank
warrior|dps
paladin|tank
hunter|dps
rogue|dps
priest|healer
shaman|healer
shaman|dps
mage|dps
warlock|dps
druid|tank
druid|healer'

# Class name -> the class id item_template's allowable_class bitmask is built
# from. Kept separate from COMBOS so a class/role pair that is not in the shipped
# teams can still be generated by hand.
CLASS_IDS='warrior|1
paladin|2
hunter|3
rogue|4
priest|5
shaman|7
mage|8
warlock|9
druid|11'

# Hardcoded for every class, on purpose and temporarily: 13446 is Major Healing
# Potion and 8952 is Roasted Quail, both confirmed present in
# tw_world.item_template on 2026-08-17. A mage wants mana potions and a warrior
# does not, so per-class consumables are folded into the same deferred curation
# artifact as the item ids.
CONSUMABLES='[{"itemId":13446,"count":20},{"itemId":8952,"count":20}]'

usage() {
    echo "usage: $(basename "$0") [<class> <role>]" >&2
    echo "       $(basename "$0") --check [<class> <role>]" >&2
    echo "       with no arguments, generates all 12 shipped combinations" >&2
    echo "       writes into $OUT_DIR" >&2
    echo "       --check re-judges the tier files already in $OUT_DIR and writes nothing" >&2
}

# --- the equip gate ---------------------------------------------------------
#
# NOTHING IS WRITTEN UNTIL EVERY PICK HAS BEEN JUDGED. A tier file is the only
# thing `tournament equip` is ever handed, so an item the class cannot wear is a
# defect of THIS script -- it just used to be discovered a day later as
# `ok=0 reason=cannot_equip(8)` in a console transcript, with a bare
# InventoryResult number and no idea which of a dozen requirements it meant.
# itemdb_equip_fault names the requirement, here, before the file exists.
#
# It re-checks what itemdb_candidates already filtered on purpose. The filter and
# the judge are two expressions of the same rules and a hand-curated file never
# went through the filter at all, so the judge is what actually holds -- which is
# also why it is reachable on its own as `--check`.
check_tier() { # <className> <role> <classId> <tier>; reads "slot<TAB>entry" on stdin
    local cname="$1" role="$2" cid="$3" tier="$4" slot id reason rc bad=0
    while IFS=$'\t' read -r slot id; do
        [ -n "${slot:-}" ] || continue
        rc=0
        reason="$(itemdb_equip_fault "$cid" "$id")" || rc=$?
        if [ "$rc" -eq 2 ]; then
            echo "FATAL: the item_template query failed judging $cname-$role tier '$tier'" >&2
            echo "       slot '$slot' (entry $id); mysql's own error is above. That is NOT" >&2
            echo "       the same as the item being wrong, so nothing is concluded." >&2
            return 2
        fi
        [ "$rc" -eq 0 ] && continue
        echo "REJECT $cname-$role tier '$tier' slot '$slot': entry $id -- $reason" >&2
        bad=1
    done
    return "$bad"
}

class_id() { # <className> -> class id, empty if unknown
    printf '%s\n' "$CLASS_IDS" | awk -F'|' -v c="$1" '$1 == c { print $2; exit }'
}

# slot<TAB>id lines on stdin -> a JSON object, keys in the order they arrived.
items_json() {
    jq -Rn '[inputs | split("\t") | {(.[0]): (.[1]|tonumber)}] | add'
}

# The best entry id for one slot at one quality.
#
# Prints the id on stdout. Returns 0 with output, 1 when this server genuinely
# stocks nothing eligible, and 2 when the QUERY ITSELF failed -- the two must not
# be conflated. An empty result from a broken query would otherwise abort with
# "no item at all for plate waist", sending whoever reads it to survey the item
# database instead of to the error message.
best_entry() { # <classId> <slot> <quality>
    local rows rc=0
    rows="$(itemdb_candidates "$1" "$2" "$3" "$NO_ILVL_CAP" 1)" || rc=$?
    [ "$rc" -eq 0 ] || return 2
    [ -n "$rows" ] || return 1
    printf '%s\n' "$rows" | awk -F'\t' 'NR == 1 { print $2 }'
}

# best_entry, with both of its failures reported. Wrapped so the two tiers report
# them identically, and so "the query broke" can never be printed as "this server
# has no such item".
pick_or_die() { # <className> <role> <classId> <slot> <quality> <file>
    local cname="$1" role="$2" cid="$3" slot="$4" quality="$5" f="$6" id rc=0
    id="$(best_entry "$cid" "$slot" "$quality")" || rc=$?
    if [ "$rc" -eq 0 ]; then printf '%s\n' "$id"; return 0; fi
    if [ "$rc" -eq 2 ]; then
        echo "FATAL: the item_template query failed for $cname-$role slot '$slot'" >&2
        echo "       (mysql's own error is above). That is NOT the same as this world" >&2
        echo "       having no such item, so nothing is concluded and $f is not written." >&2
        return 1
    fi
    echo "FATAL: no quality-$quality item at all for $cname-$role slot '$slot'" >&2
    echo "       Cannot generate a complete tier, so $f is not written -- a tier with a" >&2
    echo "       hole is the bug this path exists to fix, not a tier." >&2
    echo "       Check itemdb_armor_subclasses / itemdb_weapon_subclasses for class $cid" >&2
    echo "       before widening the query: an inequippable pick is worse than none." >&2
    return 1
}

generate_one() { # <className> <role>
    local cname="$1" role="$2" cid f
    local slot id base_pairs="" up_pairs="" base_obj up_obj

    cid="$(class_id "$cname")"
    [ -n "$cid" ] || { echo "FATAL: unknown class '$cname'" >&2; return 1; }
    case "$role" in
        tank|healer|dps) ;;
        *) echo "FATAL: role '$role' must be tank, healer or dps" >&2; return 1 ;;
    esac
    f="$OUT_DIR/$cname-$role.json"

    while IFS= read -r slot; do
        [ -n "${slot:-}" ] || continue

        id="$(pick_or_die "$cname" "$role" "$cid" "$slot" "$BASE_QUALITY" "$f")" || return 1
        base_pairs="${base_pairs}$(printf '%s\t%s' "$slot" "$id")"$'\n'

        # The upgrade tier is green in every slot, one grade above white, so it is
        # strictly better in kind whatever the item_level works out to. Falling
        # back to the base id where no green exists would make the upgrade a no-op
        # in that slot -- a donation with nothing to show for it -- so an empty
        # green cell aborts exactly like an empty white one.
        id="$(pick_or_die "$cname" "$role" "$cid" "$slot" "$UPGRADE_QUALITY" "$f")" || return 1
        up_pairs="${up_pairs}$(printf '%s\t%s' "$slot" "$id")"$'\n'
    done < <(itemdb_slots)

    # The gate, before the file exists. A rejected tier leaves the previous file
    # untouched rather than replacing a working kit with an unwearable one.
    printf '%s' "$base_pairs" | check_tier "$cname" "$role" "$cid" base || {
        echo "FATAL: $f was NOT written -- the base tier contains an item this class" >&2
        echo "       cannot equip (rejections above)" >&2; return 1; }
    printf '%s' "$up_pairs" | check_tier "$cname" "$role" "$cid" upgrade || {
        echo "FATAL: $f was NOT written -- the upgrade tier contains an item this class" >&2
        echo "       cannot equip (rejections above)" >&2; return 1; }

    base_obj="$(printf '%s' "$base_pairs" | items_json)" || return 1
    up_obj="$(printf '%s' "$up_pairs" | items_json)" || return 1

    jq -n --arg cls "$cname" --arg role "$role" \
          --argjson base "$base_obj" --argjson up "$up_obj" \
          --argjson cons "$CONSUMABLES" '
        { class: $cls,
          role: $role,
          provisional: true,
          tiers: { base:    { rank: 0, items: $base },
                   upgrade: { rank: 1, items: $up } },
          consumables: $cons }' > "$f" || {
        echo "FATAL: could not write $f" >&2; return 1; }

    # Validate what was just written, with the same library everything downstream
    # reads it through. Writing a file the library then rejects is the one
    # failure mode nobody would notice until a match was gated on it.
    gear_validate "$cname" "$role" || {
        echo "FATAL: $f was written but does not validate (faults above)" >&2; return 1; }

    echo "wrote $f"
}

# The same judgement, applied to a file that already exists -- the only way a
# hand-curated tier ever gets judged, since it never went through the generator.
check_one() { # <className> <role>
    local cname="$1" role="$2" cid t rc=0
    cid="$(class_id "$cname")"
    [ -n "$cid" ] || { echo "FATAL: unknown class '$cname'" >&2; return 1; }
    while IFS= read -r t; do
        [ -n "${t:-}" ] || continue
        gear_items "$cname" "$role" "$t" | tr '|' '\t' \
            | check_tier "$cname" "$role" "$cid" "$t" || rc=1
    done < <(gear_tiers "$cname" "$role") || return 1
    [ "$rc" -eq 0 ] && echo "ok $cname-$role"
    return "$rc"
}

command -v jq >/dev/null 2>&1 || {
    echo "FATAL: jq is not installed (apt-get install jq); run this from WSL" >&2; exit 2; }
command -v docker >/dev/null 2>&1 || {
    echo "FATAL: docker is not on PATH" >&2; exit 2; }

action=generate
if [ "${1:-}" = "--check" ]; then action=check; shift; fi

case "$#" in
    0|2) ;;
    *) usage; exit 2 ;;
esac

# --check writes nothing, so it must not create the directory either: an empty
# $OUT_DIR conjured by a read-only command reads as "the tiers were generated".
[ "$action" = "check" ] || mkdir -p "$OUT_DIR" || exit 2

run_one() { # <className> <role>
    if [ "$action" = "check" ]; then check_one "$1" "$2"; else generate_one "$1" "$2"; fi
}

rc=0
if [ "$#" -eq 2 ]; then
    run_one "$1" "$2" || rc=1
else
    while IFS='|' read -r cname role; do
        [ -n "${cname:-}" ] || continue
        run_one "$cname" "$role" || rc=1
    done < <(printf '%s\n' "$COMBOS")
fi
exit "$rc"
